#!/usr/bin/env ruby

require_relative '../lib/env'

$logger.info('Starting build')

#require 'ruby-prof'
#RubyProf.start

require_relative '../lib/assets'
require_relative '../lib/paths'
require_relative '../app/models/database'

database = Database.load

Assets.clear
Assets.build(database) # HTML pages depend on asset paths, which include hashes of contents

$logger.info('Building views...')

Dir[File.dirname(__FILE__) + '/../app/views/*.rb'].each do |path|
  next if path =~ /base_view.rb$/
  require File.absolute_path(path)
  basename = path.split('/').last.split('.').first
  class_name = basename.gsub(/(^|_)([^_]+)/) { $2.capitalize }
  klass = Object.const_get(class_name)
  klass.generate_all(database)
end

$logger.info("Rebuilt #{Paths.Dist}")

#result = RubyProf.stop
#printer = RubyProf::GraphHtmlPrinter.new(result)
#File.open('profile.html', 'w') { |f| printer.print(f) }
