#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default)

require_relative '../lib/assets'
require_relative '../app/models/database'

Database.load

Assets.clear
Assets.build # HTML pages depend on asset paths, which include hashes of contents

Dir[File.dirname(__FILE__) + '/../app/views/*.rb'].each do |path|
  next if path =~ /base_view.rb$/
  require path
  basename = path.split('/').last.split('.').first
  class_name = basename.gsub(/(^|_)([^_]+)/) { $2.capitalize }
  klass = Object.const_get(class_name)
  klass.generate_all
end
