#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default)

require_relative '../lib/states'
require_relative '../lib/race_days'

RaceDays.each do |race_day|
  puts race_day[:date].strftime('%B %-d, %Y')

  race_day[:Dem] ||= []
  race_day[:GOP] ||= []

  all_states = Set.new(race_day[:Dem] + race_day[:GOP])
    .map { |code| StatesByCode[code] }
    .to_a
    .sort_by { |state| state[:name] }

  all_states.each do |state|
    puts "  (#{race_day[:Dem].include?(state[:code]) ? 'D' : ' '}#{race_day[:GOP].include?(state[:code]) ? 'R' : ' '}) #{state[:name]}"
  end
end
