#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default, :development)

require 'webrick'

require_relative '../lib/paths'

# Serve "x.html" as just "x"
class FileHandler < WEBrick::HTTPServlet::FileHandler
  def search_file(req, res, basename)
    if file = super
      file
    else
      super(req, res, "#{basename}.html")
    end
  end
end

def on_event
  system("#{Paths.Script}/build-primaries")
  system("rspec") unless ENV['SKIP_RSPEC']
end

server = WEBrick::HTTPServer.new(Port: 3000)
server.mount('/', FileHandler, Paths.Dist)
trap("INT") { server.shutdown }

listener = Listen.to('lib', 'assets', 'templates', 'spec', only: /\.(rb|js|json|png|css|sass)$/) do |modified, added, removed|
  on_event
end

on_event
listener.start
server.start
listener.stop
