#!/usr/bin/env ruby
#
# Refreshes the delegate count and vote counts for the specified election dates
#
# Usage: update-primaries [YYYY-MM-DD ...]

require_relative '../lib/env'
require_relative '../lib/ap'

AP.poll_dates(ARGV)
exec "#{Paths.Script}/build-primaries"
