#!/usr/bin/env ruby
#
# Refreshes the delegate count and vote counts for the specified election dates
#
# Usage: update-primaries [YYYY-MM-DD ...]

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default)

require_relative '../lib/ap'

AP.poll_dates(ARGV)
exec "#{Paths.Script}/build-primaries"
