#!/usr/bin/env ruby
#
# Refreshes the pollster estimates for candidates and candidate_states
#
# Usage: update-primaries [YYYY-MM-DD ...]

require_relative '../lib/env'
require_relative '../lib/api_sources'

ApiSources.poll_pollster_primaries
exec "#{Paths.Script}/build"
