#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

Bundler.require(:default)

require_relative '../lib/ap'
require_relative '../lib/primaries_page_generator'

delegate_counts = AP.GET_del_super
election_day = AP.GET_primaries_election_day('2016-02-01')
PrimariesPageGenerator.generate(delegate_counts, election_day)
