#!/usr/bin/env ruby

require 'open-uri'

require_relative '../lib/paths'
require_relative '../lib/logger'

Url = 'https://docs.google.com/document/export?format=txt&id=1NqASd8jSJk85wZsvNlt4htsQcuDeDHBb0kQJFYzET3w'

open(Url, 'r') do |input|
  text = input.read
  open(Paths.Copy, 'w', encoding: 'utf-8') do |output|
    output.write(text)
  end
end

$logger.info("Overwrote #{Paths.Copy}")
