#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

require 'listen'

def rspec
  system('rspec', *ARGV[0..-1])
end

rspec

listener = Listen.to('app', 'lib', 'assets', 'spec', 'script', only: /(^copy)|(\.(csv|rb|js|json|png|css|sass|scss|haml|svg))$/) do |modified, added, removed|
  rspec
end

listener.start

sleep # Wait for Ctrl+C
